### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by squidCatx** [purescript-web/purescript-web-html#67]
path/Effect.Aff/foreign.js:532
                throw util.fromLeft(step);
                ^

ReferenceError: window is not defined
    at exports.window (path/Web.HTML/foreign.js:4:3)
    at path/Effect/foreign.js:12:16
    at path/Effect/foreign.js:12:16
    at __do (path/Halogen.Aff.Util/index.js:36:183)
    at runAsync (path/Effect.Aff/foreign.js:98:20)
    at run (path/Effect.Aff/foreign.js:333:22)
    at path/Effect.Aff/foreign.js:639:15
    at drain (path/Effect.Aff/foreign.js:120:9)
    at Object.enqueue (path/Effect.Aff/foreign.js:141:11)
    at Object.run (path/Effect.Aff/foreign.js:638:23)

Node.js v17.2.0

should we use globalThis   instead of window ?

**Comment by thomashoneyman** [comment]
This library is intended for use in the browser, which is why it expects the window to be available. On Node, you can provide a shim for the window object if you need this library to be available there.

**Comment by squidCatx** [comment]
i see  thanks
